/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Characters: typeof import('./src/components/Characters.vue')['default']
    Filters: typeof import('./src/components/Filters.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    QAvatar: typeof import('quasar')['QAvatar']
    QBadge: typeof import('quasar')['QBadge']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardSection: typeof import('quasar')['QCardSection']
    QFooter: typeof import('quasar')['QFooter']
    QHeader: typeof import('quasar')['QHeader']
    QImg: typeof import('quasar')['QImg']
    QInput: typeof import('quasar')['QInput']
    QLayout: typeof import('quasar')['QLayout']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QPagination: typeof import('quasar')['QPagination']
    QParallax: typeof import('quasar')['QParallax']
    QToggle: typeof import('quasar')['QToggle']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
