/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Characters: typeof import('./src/components/Characters.vue')['default']
    Filters: typeof import('./src/components/Filters.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    QAvatar: typeof import('quasar')['QAvatar']
    QBadge: typeof import('quasar')['QBadge']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardActions: typeof import('quasar')['QCardActions']
    QCardSection: typeof import('quasar')['QCardSection']
    QHeader: typeof import('quasar')['QHeader']
    QImg: typeof import('quasar')['QImg']
    QInput: typeof import('quasar')['QInput']
    QLayout: typeof import('quasar')['QLayout']
    QPagination: typeof import('quasar')['QPagination']
    QSeparator: typeof import('quasar')['QSeparator']
    QSlideTransition: typeof import('quasar')['QSlideTransition']
    QSpace: typeof import('quasar')['QSpace']
    QToggle: typeof import('quasar')['QToggle']
    QToolbar: typeof import('quasar')['QToolbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
